var searchData=
[
  ['imprimir_20el_20mensaje_20recibido_20y_20mantenerlo_20visible_20durante_20un_20segundo_20antes_20de_20regresar_20al_20código_20que_20la_20llamó_0',['PURPOSE: La función mostrarMensaje() es una función simple y útil para mostrar mensajes informativos o de alerta. Se encarga de limpiar la pantalla, imprimir el mensaje recibido y mantenerlo visible durante un segundo antes de regresar al código que la llamó.',['../sketch_8ino.html#autotoc_md59',1,'']]],
  ['incorrecta_20y_20se_20superan_20los_20intentos_20permitidos_20bloquea_20el_20acceso_1',['PURPOSE: La función permite el ingreso de una clave por parte del usuario y la compara con una clave predefinida. Si la clave es correcta, habilita el acceso. Si la clave es incorrecta y se superan los intentos permitidos, bloquea el acceso.',['../sketch_8ino.html#autotoc_md19',1,'']]],
  ['indicar_20alarmas_20o_20solicitar_20la_20clave_20de_20acceso_2',['PURPOSE: Permite gestionar los diferentes estados del sistema (&apos;0&apos;, &apos;1&apos;, &apos;2&apos; y &apos;3&apos;), ejecutando las acciones correspondientes a cada uno, como mostrar el menú principal, monitorear sensores, indicar alarmas o solicitar la clave de acceso.',['../sketch_8ino.html#autotoc_md11',1,'']]],
  ['información_20de_20movimiento_20detectado_20y_20respondiendo_20en_20caso_20de_20que_20se_20detecte_20movimiento_20llamando_20a_20la_20función_20estados_3',['PURPOSE: La función MonitoreoMovimiento() funciona como un detector de movimiento durante un período de 3 segundos,  actualizando la pantalla LCD con la información de movimiento detectado y  respondiendo en caso de que se detecte movimiento llamando a la función Estados().',['../sketch_8ino.html#autotoc_md55',1,'']]],
  ['informativos_20o_20de_20alerta_20se_20encarga_20de_20limpiar_20la_20pantalla_20imprimir_20el_20mensaje_20recibido_20y_20mantenerlo_20visible_20durante_20un_20segundo_20antes_20de_20regresar_20al_20código_20que_20la_20llamó_4',['PURPOSE: La función mostrarMensaje() es una función simple y útil para mostrar mensajes informativos o de alerta. Se encarga de limpiar la pantalla, imprimir el mensaje recibido y mantenerlo visible durante un segundo antes de regresar al código que la llamó.',['../sketch_8ino.html#autotoc_md59',1,'']]],
  ['ingresada_20caracter_20a_20caracter_20en_20un_20array_20y_20oculta_20los_20caracteres_20reales_20mostrando_20asteriscos_20en_20la_20pantalla_20lcd_5',['PURPOSE:  Proporciona un tiempo límite de espera por tecla presionada para evitar entradas erróneas. Almacena la clave ingresada caracter a caracter en un array y oculta los caracteres reales mostrando asteriscos en la pantalla LCD.',['../sketch_8ino.html#autotoc_md15',1,'']]],
  ['ingresado_20en_20el_20keypad_6',['ingresado en el keypad',['../sketch_8ino.html#autotoc_md43',1,'PURPOSE: Modifica el valor de umbrLuzHigh con el valor ingresado en el keypad'],['../sketch_8ino.html#autotoc_md47',1,'PURPOSE: Modifica el valor de umbrLuzLow con el valor ingresado en el keypad'],['../sketch_8ino.html#autotoc_md35',1,'PURPOSE: Modifica el valor de umbrTempHigh con el valor ingresado en el keypad'],['../sketch_8ino.html#autotoc_md39',1,'PURPOSE: Modifica el valor de umbrTempLow con el valor ingresado en el keypad']]],
  ['ingreso_20de_20una_20clave_20por_20parte_20del_20usuario_20y_20la_20compara_20con_20una_20clave_20predefinida_20si_20la_20clave_20es_20correcta_20habilita_20el_20acceso_20si_20la_20clave_20es_20incorrecta_20y_20se_20superan_20los_20intentos_20permitidos_20bloquea_20el_20acceso_7',['PURPOSE: La función permite el ingreso de una clave por parte del usuario y la compara con una clave predefinida. Si la clave es correcta, habilita el acceso. Si la clave es incorrecta y se superan los intentos permitidos, bloquea el acceso.',['../sketch_8ino.html#autotoc_md19',1,'']]],
  ['inicializa_20la_20comunicación_20serial_20para_20enviar_20o_20recibir_20datos_20y_20prepara_20librerías_20para_20sensores_20u_20otros_20componentes_20electrónicos_8',['PURPOSE: Configura los pines para controlar dispositivos externos como LEDs, inicializa la comunicación serial para enviar o recibir datos y prepara librerías para sensores u otros componentes electrónicos.',['../sketch_8ino.html#autotoc_md3',1,'']]],
  ['int_9',['int',['../sketch_8ino.html#autotoc_md69',1,'PARAMS:    int'],['../sketch_8ino.html#autotoc_md74',1,'PARAMS:    int'],['../sketch_8ino.html#autotoc_md65',1,'PARAMS: char, char, char, int']]],
  ['int_20luz_10',['int luz',['../sketch_8ino.html#autotoc_md79',1,'PARAMS:    int luz'],['../sketch_8ino.html#autotoc_md84',1,'PARAMS:    int luz']]],
  ['intensidad_20de_20cada_20color_20por_20separado_20rojo_20verde_20azul_20y_20especificar_20el_20tiempo_20de_20visualización_20del_20color_20seleccionado_11',['PURPOSE: Permite ajustar la intensidad de cada color por separado (rojo, verde, azul) y especificar el tiempo de visualización del color seleccionado.',['../sketch_8ino.html#autotoc_md67',1,'']]],
  ['intentos_12',['intentos',['../sketch_8ino.html#aa94c7b86d418ed6114b2278c43734e57',1,'sketch.ino']]],
  ['intentos_20permitidos_20bloquea_20el_20acceso_13',['PURPOSE: La función permite el ingreso de una clave por parte del usuario y la compara con una clave predefinida. Si la clave es correcta, habilita el acceso. Si la clave es incorrecta y se superan los intentos permitidos, bloquea el acceso.',['../sketch_8ino.html#autotoc_md19',1,'']]],
  ['interactuar_20con_20el_20menú_20principal_20seleccionando_20opciones_20para_20configurar_20umbrales_20o_20cambiar_20el_20modo_20de_20funcionamiento_20llamando_20a_20las_20funciones_20correspondientes_20si_20se_20introduce_20una_20opción_20no_20válida_20simplemente_20se_20limpia_20la_20selección_20y_20se_20vuelve_20a_20mostrar_20el_20menú_14',['PURPOSE: Permite al usuario interactuar con el menú principal, seleccionando opciones para configurar umbrales o cambiar el modo de funcionamiento llamando a las funciones correspondientes. Si se introduce una opción no válida, simplemente se limpia la selección y se vuelve a mostrar el menú.',['../sketch_8ino.html#autotoc_md31',1,'']]],
  ['introduce_20una_20opción_20no_20válida_20simplemente_20se_20limpia_20la_20selección_20y_20se_20vuelve_20a_20mostrar_20el_20menú_15',['PURPOSE: Permite al usuario interactuar con el menú principal, seleccionando opciones para configurar umbrales o cambiar el modo de funcionamiento llamando a las funciones correspondientes. Si se introduce una opción no válida, simplemente se limpia la selección y se vuelve a mostrar el menú.',['../sketch_8ino.html#autotoc_md31',1,'']]]
];
