var searchData=
[
  ['o_20cambiar_20el_20modo_20de_20funcionamiento_20llamando_20a_20las_20funciones_20correspondientes_20si_20se_20introduce_20una_20opción_20no_20válida_20simplemente_20se_20limpia_20la_20selección_20y_20se_20vuelve_20a_20mostrar_20el_20menú_0',['PURPOSE: Permite al usuario interactuar con el menú principal, seleccionando opciones para configurar umbrales o cambiar el modo de funcionamiento llamando a las funciones correspondientes. Si se introduce una opción no válida, simplemente se limpia la selección y se vuelve a mostrar el menú.',['../sketch_8ino.html#autotoc_md31',1,'']]],
  ['o_20de_20alerta_20se_20encarga_20de_20limpiar_20la_20pantalla_20imprimir_20el_20mensaje_20recibido_20y_20mantenerlo_20visible_20durante_20un_20segundo_20antes_20de_20regresar_20al_20código_20que_20la_20llamó_1',['PURPOSE: La función mostrarMensaje() es una función simple y útil para mostrar mensajes informativos o de alerta. Se encarga de limpiar la pantalla, imprimir el mensaje recibido y mantenerlo visible durante un segundo antes de regresar al código que la llamó.',['../sketch_8ino.html#autotoc_md59',1,'']]],
  ['o_20directamente_20por_20el_20número_20de_20la_20opción_20del_201_20al_206_20al_20seleccionar_20una_20opción_20válida_20se_20llama_20a_20la_20función_20ejecutaropcion_20para_20procesarla_2',['PURPOSE:  Muestra el menú principal en la pantalla LCD, permite el desplazamiento automático para visualizar todas las opciones y ofrece dos formas de selección: por tecla de navegación (&apos;A&apos; y &apos;B&apos;) o directamente por el número de la opción (del 1 al 6). Al seleccionar una opción válida, se llama a la función ejecutarOpcion() para procesarla.',['../sketch_8ino.html#autotoc_md23',1,'']]],
  ['o_20recibir_20datos_20y_20prepara_20librerías_20para_20sensores_20u_20otros_20componentes_20electrónicos_3',['PURPOSE: Configura los pines para controlar dispositivos externos como LEDs, inicializa la comunicación serial para enviar o recibir datos y prepara librerías para sensores u otros componentes electrónicos.',['../sketch_8ino.html#autotoc_md3',1,'']]],
  ['o_20se_20excede_20el_20tiempo_20la_20función_20finaliza_20sin_20procesar_20ninguna_20opción_4',['PURPOSE:  Proporciona un tiempo de espera para que el usuario seleccione una opción en el teclado.  Si se selecciona una opción válida dentro del tiempo límite, se procesa la opción llamando a la función ejecutarOpcion(). Si no se selecciona ninguna opción o se excede el tiempo, la función finaliza sin procesar ninguna opción.',['../sketch_8ino.html#autotoc_md27',1,'']]],
  ['o_20solicitar_20la_20clave_20de_20acceso_5',['PURPOSE: Permite gestionar los diferentes estados del sistema (&apos;0&apos;, &apos;1&apos;, &apos;2&apos; y &apos;3&apos;), ejecutando las acciones correspondientes a cada uno, como mostrar el menú principal, monitorear sensores, indicar alarmas o solicitar la clave de acceso.',['../sketch_8ino.html#autotoc_md11',1,'']]],
  ['oculta_20los_20caracteres_20reales_20mostrando_20asteriscos_20en_20la_20pantalla_20lcd_6',['PURPOSE:  Proporciona un tiempo límite de espera por tecla presionada para evitar entradas erróneas. Almacena la clave ingresada caracter a caracter en un array y oculta los caracteres reales mostrando asteriscos en la pantalla LCD.',['../sketch_8ino.html#autotoc_md15',1,'']]],
  ['ofrece_20dos_20formas_20de_20selección_3a_20por_20tecla_20de_20navegación_20a_20y_20b_20o_20directamente_20por_20el_20número_20de_20la_20opción_20del_201_20al_206_20al_20seleccionar_20una_20opción_20válida_20se_20llama_20a_20la_20función_20ejecutaropcion_20para_20procesarla_7',['PURPOSE:  Muestra el menú principal en la pantalla LCD, permite el desplazamiento automático para visualizar todas las opciones y ofrece dos formas de selección: por tecla de navegación (&apos;A&apos; y &apos;B&apos;) o directamente por el número de la opción (del 1 al 6). Al seleccionar una opción válida, se llama a la función ejecutarOpcion() para procesarla.',['../sketch_8ino.html#autotoc_md23',1,'']]],
  ['opción_8',['PURPOSE:  Proporciona un tiempo de espera para que el usuario seleccione una opción en el teclado.  Si se selecciona una opción válida dentro del tiempo límite, se procesa la opción llamando a la función ejecutarOpcion(). Si no se selecciona ninguna opción o se excede el tiempo, la función finaliza sin procesar ninguna opción.',['../sketch_8ino.html#autotoc_md27',1,'']]],
  ['opción_20del_201_20al_206_20al_20seleccionar_20una_20opción_20válida_20se_20llama_20a_20la_20función_20ejecutaropcion_20para_20procesarla_9',['PURPOSE:  Muestra el menú principal en la pantalla LCD, permite el desplazamiento automático para visualizar todas las opciones y ofrece dos formas de selección: por tecla de navegación (&apos;A&apos; y &apos;B&apos;) o directamente por el número de la opción (del 1 al 6). Al seleccionar una opción válida, se llama a la función ejecutarOpcion() para procesarla.',['../sketch_8ino.html#autotoc_md23',1,'']]],
  ['opción_20en_20el_20teclado_20si_20se_20selecciona_20una_20opción_20válida_20dentro_20del_20tiempo_20límite_20se_20procesa_20la_20opción_20llamando_20a_20la_20función_20ejecutaropcion_20si_20no_20se_20selecciona_20ninguna_20opción_20o_20se_20excede_20el_20tiempo_20la_20función_20finaliza_20sin_20procesar_20ninguna_20opción_10',['PURPOSE:  Proporciona un tiempo de espera para que el usuario seleccione una opción en el teclado.  Si se selecciona una opción válida dentro del tiempo límite, se procesa la opción llamando a la función ejecutarOpcion(). Si no se selecciona ninguna opción o se excede el tiempo, la función finaliza sin procesar ninguna opción.',['../sketch_8ino.html#autotoc_md27',1,'']]],
  ['opción_20llamando_20a_20la_20función_20ejecutaropcion_20si_20no_20se_20selecciona_20ninguna_20opción_20o_20se_20excede_20el_20tiempo_20la_20función_20finaliza_20sin_20procesar_20ninguna_20opción_11',['PURPOSE:  Proporciona un tiempo de espera para que el usuario seleccione una opción en el teclado.  Si se selecciona una opción válida dentro del tiempo límite, se procesa la opción llamando a la función ejecutarOpcion(). Si no se selecciona ninguna opción o se excede el tiempo, la función finaliza sin procesar ninguna opción.',['../sketch_8ino.html#autotoc_md27',1,'']]],
  ['opción_20no_20válida_20simplemente_20se_20limpia_20la_20selección_20y_20se_20vuelve_20a_20mostrar_20el_20menú_12',['PURPOSE: Permite al usuario interactuar con el menú principal, seleccionando opciones para configurar umbrales o cambiar el modo de funcionamiento llamando a las funciones correspondientes. Si se introduce una opción no válida, simplemente se limpia la selección y se vuelve a mostrar el menú.',['../sketch_8ino.html#autotoc_md31',1,'']]],
  ['opción_20o_20se_20excede_20el_20tiempo_20la_20función_20finaliza_20sin_20procesar_20ninguna_20opción_13',['PURPOSE:  Proporciona un tiempo de espera para que el usuario seleccione una opción en el teclado.  Si se selecciona una opción válida dentro del tiempo límite, se procesa la opción llamando a la función ejecutarOpcion(). Si no se selecciona ninguna opción o se excede el tiempo, la función finaliza sin procesar ninguna opción.',['../sketch_8ino.html#autotoc_md27',1,'']]],
  ['opción_20válida_20dentro_20del_20tiempo_20límite_20se_20procesa_20la_20opción_20llamando_20a_20la_20función_20ejecutaropcion_20si_20no_20se_20selecciona_20ninguna_20opción_20o_20se_20excede_20el_20tiempo_20la_20función_20finaliza_20sin_20procesar_20ninguna_20opción_14',['PURPOSE:  Proporciona un tiempo de espera para que el usuario seleccione una opción en el teclado.  Si se selecciona una opción válida dentro del tiempo límite, se procesa la opción llamando a la función ejecutarOpcion(). Si no se selecciona ninguna opción o se excede el tiempo, la función finaliza sin procesar ninguna opción.',['../sketch_8ino.html#autotoc_md27',1,'']]],
  ['opción_20válida_20se_20llama_20a_20la_20función_20ejecutaropcion_20para_20procesarla_15',['PURPOSE:  Muestra el menú principal en la pantalla LCD, permite el desplazamiento automático para visualizar todas las opciones y ofrece dos formas de selección: por tecla de navegación (&apos;A&apos; y &apos;B&apos;) o directamente por el número de la opción (del 1 al 6). Al seleccionar una opción válida, se llama a la función ejecutarOpcion() para procesarla.',['../sketch_8ino.html#autotoc_md23',1,'']]],
  ['opciones_20para_20configurar_20umbrales_20o_20cambiar_20el_20modo_20de_20funcionamiento_20llamando_20a_20las_20funciones_20correspondientes_20si_20se_20introduce_20una_20opción_20no_20válida_20simplemente_20se_20limpia_20la_20selección_20y_20se_20vuelve_20a_20mostrar_20el_20menú_16',['PURPOSE: Permite al usuario interactuar con el menú principal, seleccionando opciones para configurar umbrales o cambiar el modo de funcionamiento llamando a las funciones correspondientes. Si se introduce una opción no válida, simplemente se limpia la selección y se vuelve a mostrar el menú.',['../sketch_8ino.html#autotoc_md31',1,'']]],
  ['opciones_20y_20ofrece_20dos_20formas_20de_20selección_3a_20por_20tecla_20de_20navegación_20a_20y_20b_20o_20directamente_20por_20el_20número_20de_20la_20opción_20del_201_20al_206_20al_20seleccionar_20una_20opción_20válida_20se_20llama_20a_20la_20función_20ejecutaropcion_20para_20procesarla_17',['PURPOSE:  Muestra el menú principal en la pantalla LCD, permite el desplazamiento automático para visualizar todas las opciones y ofrece dos formas de selección: por tecla de navegación (&apos;A&apos; y &apos;B&apos;) o directamente por el número de la opción (del 1 al 6). Al seleccionar una opción válida, se llama a la función ejecutarOpcion() para procesarla.',['../sketch_8ino.html#autotoc_md23',1,'']]],
  ['opcionseleccionada_18',['opcionSeleccionada',['../sketch_8ino.html#afd0cb2dab9577b465dab16888b8380f9',1,'sketch.ino']]],
  ['otros_20componentes_20electrónicos_19',['PURPOSE: Configura los pines para controlar dispositivos externos como LEDs, inicializa la comunicación serial para enviar o recibir datos y prepara librerías para sensores u otros componentes electrónicos.',['../sketch_8ino.html#autotoc_md3',1,'']]]
];
