var searchData=
[
  ['reales_20mostrando_20asteriscos_20en_20la_20pantalla_20lcd_0',['PURPOSE:  Proporciona un tiempo límite de espera por tecla presionada para evitar entradas erróneas. Almacena la clave ingresada caracter a caracter en un array y oculta los caracteres reales mostrando asteriscos en la pantalla LCD.',['../sketch_8ino.html#autotoc_md15',1,'']]],
  ['realizar_20cambios_1',['PURPOSE: La función reset() solicita confirmación para realizar un reinicio de los umbrales, restaurándolos a sus valores por defecto. Si se confirma, actualiza los valores y vuelve al menú principal. Si se cancela, regresa al menú principal sin realizar cambios.',['../sketch_8ino.html#autotoc_md91',1,'']]],
  ['realizar_20un_20reinicio_20de_20los_20umbrales_20restaurándolos_20a_20sus_20valores_20por_20defecto_20si_20se_20confirma_20actualiza_20los_20valores_20y_20vuelve_20al_20menú_20principal_20si_20se_20cancela_20regresa_20al_20menú_20principal_20sin_20realizar_20cambios_2',['PURPOSE: La función reset() solicita confirmación para realizar un reinicio de los umbrales, restaurándolos a sus valores por defecto. Si se confirma, actualiza los valores y vuelve al menú principal. Si se cancela, regresa al menú principal sin realizar cambios.',['../sketch_8ino.html#autotoc_md91',1,'']]],
  ['recibido_20y_20mantenerlo_20visible_20durante_20un_20segundo_20antes_20de_20regresar_20al_20código_20que_20la_20llamó_3',['PURPOSE: La función mostrarMensaje() es una función simple y útil para mostrar mensajes informativos o de alerta. Se encarga de limpiar la pantalla, imprimir el mensaje recibido y mantenerlo visible durante un segundo antes de regresar al código que la llamó.',['../sketch_8ino.html#autotoc_md59',1,'']]],
  ['recibir_20datos_20y_20prepara_20librerías_20para_20sensores_20u_20otros_20componentes_20electrónicos_4',['PURPOSE: Configura los pines para controlar dispositivos externos como LEDs, inicializa la comunicación serial para enviar o recibir datos y prepara librerías para sensores u otros componentes electrónicos.',['../sketch_8ino.html#autotoc_md3',1,'']]],
  ['regresa_20al_20menú_20principal_20sin_20realizar_20cambios_5',['PURPOSE: La función reset() solicita confirmación para realizar un reinicio de los umbrales, restaurándolos a sus valores por defecto. Si se confirma, actualiza los valores y vuelve al menú principal. Si se cancela, regresa al menú principal sin realizar cambios.',['../sketch_8ino.html#autotoc_md91',1,'']]],
  ['regresar_20al_20código_20que_20la_20llamó_6',['PURPOSE: La función mostrarMensaje() es una función simple y útil para mostrar mensajes informativos o de alerta. Se encarga de limpiar la pantalla, imprimir el mensaje recibido y mantenerlo visible durante un segundo antes de regresar al código que la llamó.',['../sketch_8ino.html#autotoc_md59',1,'']]],
  ['reinicio_20de_20los_20umbrales_20restaurándolos_20a_20sus_20valores_20por_20defecto_20si_20se_20confirma_20actualiza_20los_20valores_20y_20vuelve_20al_20menú_20principal_20si_20se_20cancela_20regresa_20al_20menú_20principal_20sin_20realizar_20cambios_7',['PURPOSE: La función reset() solicita confirmación para realizar un reinicio de los umbrales, restaurándolos a sus valores por defecto. Si se confirma, actualiza los valores y vuelve al menú principal. Si se cancela, regresa al menú principal sin realizar cambios.',['../sketch_8ino.html#autotoc_md91',1,'']]],
  ['repetidamente_20llamando_20a_20la_20función_20estados_20para_20gestionar_20el_20estado_20actual_20del_20sistema_20y_20ejecutar_20las_20acciones_20correspondientes_8',['PURPOSE: La función loop() es el núcleo del programa. Se ejecuta repetidamente, llamando a la función Estados() para gestionar el estado actual del sistema y ejecutar las acciones correspondientes.',['../sketch_8ino.html#autotoc_md7',1,'']]],
  ['reproducir_20tres_20notas_20con_20duraciones_20predeterminadas_20y_20pausas_20entre_20ellas_9',['PURPOSE: Permite reproducir tres notas con duraciones predeterminadas y pausas entre ellas.',['../sketch_8ino.html#autotoc_md63',1,'']]],
  ['reset_10',['reset',['../sketch_8ino.html#autotoc_md88',1,'NAME: reset'],['../sketch_8ino.html#ad20897c5c8bd47f5d4005989bead0e55',1,'reset():&#160;sketch.ino']]],
  ['reset_20solicita_20confirmación_20para_20realizar_20un_20reinicio_20de_20los_20umbrales_20restaurándolos_20a_20sus_20valores_20por_20defecto_20si_20se_20confirma_20actualiza_20los_20valores_20y_20vuelve_20al_20menú_20principal_20si_20se_20cancela_20regresa_20al_20menú_20principal_20sin_20realizar_20cambios_11',['PURPOSE: La función reset() solicita confirmación para realizar un reinicio de los umbrales, restaurándolos a sus valores por defecto. Si se confirma, actualiza los valores y vuelve al menú principal. Si se cancela, regresa al menú principal sin realizar cambios.',['../sketch_8ino.html#autotoc_md91',1,'']]],
  ['respondiendo_20a_20la_20pulsación_20de_20una_20tecla_20específica_12',['PURPOSE: La función Monitoreo() funciona como un bucle principal que se ejecuta continuamente, monitoreando la temperatura, la luminosidad, y respondiendo a la pulsación de una tecla específica (*)',['../sketch_8ino.html#autotoc_md51',1,'']]],
  ['respondiendo_20en_20caso_20de_20que_20se_20detecte_20movimiento_20llamando_20a_20la_20función_20estados_13',['PURPOSE: La función MonitoreoMovimiento() funciona como un detector de movimiento durante un período de 3 segundos,  actualizando la pantalla LCD con la información de movimiento detectado y  respondiendo en caso de que se detecte movimiento llamando a la función Estados().',['../sketch_8ino.html#autotoc_md55',1,'']]],
  ['restaurándolos_20a_20sus_20valores_20por_20defecto_20si_20se_20confirma_20actualiza_20los_20valores_20y_20vuelve_20al_20menú_20principal_20si_20se_20cancela_20regresa_20al_20menú_20principal_20sin_20realizar_20cambios_14',['PURPOSE: La función reset() solicita confirmación para realizar un reinicio de los umbrales, restaurándolos a sus valores por defecto. Si se confirma, actualiza los valores y vuelve al menú principal. Si se cancela, regresa al menú principal sin realizar cambios.',['../sketch_8ino.html#autotoc_md91',1,'']]],
  ['return_3a_20nada_15',['RETURN: nada',['../sketch_8ino.html#autotoc_md10',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md14',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md18',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md22',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md26',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md30',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md34',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md38',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md42',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md46',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md50',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md54',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md58',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md62',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md66',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md70',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md75',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md80',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md85',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md90',1,'RETURN:   nada'],['../sketch_8ino.html#autotoc_md2',1,'RETURN: nada'],['../sketch_8ino.html#autotoc_md6',1,'RETURN: nada']]],
  ['rojo_20verde_20azul_20y_20especificar_20el_20tiempo_20de_20visualización_20del_20color_20seleccionado_16',['PURPOSE: Permite ajustar la intensidad de cada color por separado (rojo, verde, azul) y especificar el tiempo de visualización del color seleccionado.',['../sketch_8ino.html#autotoc_md67',1,'']]],
  ['rowpins_17',['rowPins',['../sketch_8ino.html#a6d6753e0ae098b31e2f84d4024e361cf',1,'sketch.ino']]],
  ['rows_18',['ROWS',['../sketch_8ino.html#a829655a147df70dd4cc94eae40a2204e',1,'sketch.ino']]]
];
