var searchData=
[
  ['finaliza_20sin_20procesar_20ninguna_20opción_0',['PURPOSE:  Proporciona un tiempo de espera para que el usuario seleccione una opción en el teclado.  Si se selecciona una opción válida dentro del tiempo límite, se procesa la opción llamando a la función ejecutarOpcion(). Si no se selecciona ninguna opción o se excede el tiempo, la función finaliza sin procesar ninguna opción.',['../sketch_8ino.html#autotoc_md27',1,'']]],
  ['formas_20de_20selección_3a_20por_20tecla_20de_20navegación_20a_20y_20b_20o_20directamente_20por_20el_20número_20de_20la_20opción_20del_201_20al_206_20al_20seleccionar_20una_20opción_20válida_20se_20llama_20a_20la_20función_20ejecutaropcion_20para_20procesarla_1',['PURPOSE:  Muestra el menú principal en la pantalla LCD, permite el desplazamiento automático para visualizar todas las opciones y ofrece dos formas de selección: por tecla de navegación (&apos;A&apos; y &apos;B&apos;) o directamente por el número de la opción (del 1 al 6). Al seleccionar una opción válida, se llama a la función ejecutarOpcion() para procesarla.',['../sketch_8ino.html#autotoc_md23',1,'']]],
  ['función_20ejecutaropcion_20para_20procesarla_2',['PURPOSE:  Muestra el menú principal en la pantalla LCD, permite el desplazamiento automático para visualizar todas las opciones y ofrece dos formas de selección: por tecla de navegación (&apos;A&apos; y &apos;B&apos;) o directamente por el número de la opción (del 1 al 6). Al seleccionar una opción válida, se llama a la función ejecutarOpcion() para procesarla.',['../sketch_8ino.html#autotoc_md23',1,'']]],
  ['función_20ejecutaropcion_20si_20no_20se_20selecciona_20ninguna_20opción_20o_20se_20excede_20el_20tiempo_20la_20función_20finaliza_20sin_20procesar_20ninguna_20opción_3',['PURPOSE:  Proporciona un tiempo de espera para que el usuario seleccione una opción en el teclado.  Si se selecciona una opción válida dentro del tiempo límite, se procesa la opción llamando a la función ejecutarOpcion(). Si no se selecciona ninguna opción o se excede el tiempo, la función finaliza sin procesar ninguna opción.',['../sketch_8ino.html#autotoc_md27',1,'']]],
  ['función_20estados_4',['PURPOSE: La función MonitoreoMovimiento() funciona como un detector de movimiento durante un período de 3 segundos,  actualizando la pantalla LCD con la información de movimiento detectado y  respondiendo en caso de que se detecte movimiento llamando a la función Estados().',['../sketch_8ino.html#autotoc_md55',1,'']]],
  ['función_20estados_20para_20gestionar_20el_20estado_20actual_20del_20sistema_20y_20ejecutar_20las_20acciones_20correspondientes_5',['PURPOSE: La función loop() es el núcleo del programa. Se ejecuta repetidamente, llamando a la función Estados() para gestionar el estado actual del sistema y ejecutar las acciones correspondientes.',['../sketch_8ino.html#autotoc_md7',1,'']]],
  ['función_20finaliza_20sin_20procesar_20ninguna_20opción_6',['PURPOSE:  Proporciona un tiempo de espera para que el usuario seleccione una opción en el teclado.  Si se selecciona una opción válida dentro del tiempo límite, se procesa la opción llamando a la función ejecutarOpcion(). Si no se selecciona ninguna opción o se excede el tiempo, la función finaliza sin procesar ninguna opción.',['../sketch_8ino.html#autotoc_md27',1,'']]],
  ['función_20loop_20es_20el_20núcleo_20del_20programa_20se_20ejecuta_20repetidamente_20llamando_20a_20la_20función_20estados_20para_20gestionar_20el_20estado_20actual_20del_20sistema_20y_20ejecutar_20las_20acciones_20correspondientes_7',['PURPOSE: La función loop() es el núcleo del programa. Se ejecuta repetidamente, llamando a la función Estados() para gestionar el estado actual del sistema y ejecutar las acciones correspondientes.',['../sketch_8ino.html#autotoc_md7',1,'']]],
  ['función_20monitoreo_20funciona_20como_20un_20bucle_20principal_20que_20se_20ejecuta_20continuamente_20monitoreando_20la_20temperatura_20la_20luminosidad_20y_20respondiendo_20a_20la_20pulsación_20de_20una_20tecla_20específica_8',['PURPOSE: La función Monitoreo() funciona como un bucle principal que se ejecuta continuamente, monitoreando la temperatura, la luminosidad, y respondiendo a la pulsación de una tecla específica (*)',['../sketch_8ino.html#autotoc_md51',1,'']]],
  ['función_20monitoreomovimiento_20funciona_20como_20un_20detector_20de_20movimiento_20durante_20un_20período_20de_203_20segundos_20actualizando_20la_20pantalla_20lcd_20con_20la_20información_20de_20movimiento_20detectado_20y_20respondiendo_20en_20caso_20de_20que_20se_20detecte_20movimiento_20llamando_20a_20la_20función_20estados_9',['PURPOSE: La función MonitoreoMovimiento() funciona como un detector de movimiento durante un período de 3 segundos,  actualizando la pantalla LCD con la información de movimiento detectado y  respondiendo en caso de que se detecte movimiento llamando a la función Estados().',['../sketch_8ino.html#autotoc_md55',1,'']]],
  ['función_20mostrarmensaje_20es_20una_20función_20simple_20y_20útil_20para_20mostrar_20mensajes_20informativos_20o_20de_20alerta_20se_20encarga_20de_20limpiar_20la_20pantalla_20imprimir_20el_20mensaje_20recibido_20y_20mantenerlo_20visible_20durante_20un_20segundo_20antes_20de_20regresar_20al_20código_20que_20la_20llamó_10',['PURPOSE: La función mostrarMensaje() es una función simple y útil para mostrar mensajes informativos o de alerta. Se encarga de limpiar la pantalla, imprimir el mensaje recibido y mantenerlo visible durante un segundo antes de regresar al código que la llamó.',['../sketch_8ino.html#autotoc_md59',1,'']]],
  ['función_20permite_20el_20ingreso_20de_20una_20clave_20por_20parte_20del_20usuario_20y_20la_20compara_20con_20una_20clave_20predefinida_20si_20la_20clave_20es_20correcta_20habilita_20el_20acceso_20si_20la_20clave_20es_20incorrecta_20y_20se_20superan_20los_20intentos_20permitidos_20bloquea_20el_20acceso_11',['PURPOSE: La función permite el ingreso de una clave por parte del usuario y la compara con una clave predefinida. Si la clave es correcta, habilita el acceso. Si la clave es incorrecta y se superan los intentos permitidos, bloquea el acceso.',['../sketch_8ino.html#autotoc_md19',1,'']]],
  ['función_20reset_20solicita_20confirmación_20para_20realizar_20un_20reinicio_20de_20los_20umbrales_20restaurándolos_20a_20sus_20valores_20por_20defecto_20si_20se_20confirma_20actualiza_20los_20valores_20y_20vuelve_20al_20menú_20principal_20si_20se_20cancela_20regresa_20al_20menú_20principal_20sin_20realizar_20cambios_12',['PURPOSE: La función reset() solicita confirmación para realizar un reinicio de los umbrales, restaurándolos a sus valores por defecto. Si se confirma, actualiza los valores y vuelve al menú principal. Si se cancela, regresa al menú principal sin realizar cambios.',['../sketch_8ino.html#autotoc_md91',1,'']]],
  ['función_20simple_20y_20útil_20para_20mostrar_20mensajes_20informativos_20o_20de_20alerta_20se_20encarga_20de_20limpiar_20la_20pantalla_20imprimir_20el_20mensaje_20recibido_20y_20mantenerlo_20visible_20durante_20un_20segundo_20antes_20de_20regresar_20al_20código_20que_20la_20llamó_13',['PURPOSE: La función mostrarMensaje() es una función simple y útil para mostrar mensajes informativos o de alerta. Se encarga de limpiar la pantalla, imprimir el mensaje recibido y mantenerlo visible durante un segundo antes de regresar al código que la llamó.',['../sketch_8ino.html#autotoc_md59',1,'']]],
  ['funciona_20como_20un_20bucle_20principal_20que_20se_20ejecuta_20continuamente_20monitoreando_20la_20temperatura_20la_20luminosidad_20y_20respondiendo_20a_20la_20pulsación_20de_20una_20tecla_20específica_14',['PURPOSE: La función Monitoreo() funciona como un bucle principal que se ejecuta continuamente, monitoreando la temperatura, la luminosidad, y respondiendo a la pulsación de una tecla específica (*)',['../sketch_8ino.html#autotoc_md51',1,'']]],
  ['funciona_20como_20un_20detector_20de_20movimiento_20durante_20un_20período_20de_203_20segundos_20actualizando_20la_20pantalla_20lcd_20con_20la_20información_20de_20movimiento_20detectado_20y_20respondiendo_20en_20caso_20de_20que_20se_20detecte_20movimiento_20llamando_20a_20la_20función_20estados_15',['PURPOSE: La función MonitoreoMovimiento() funciona como un detector de movimiento durante un período de 3 segundos,  actualizando la pantalla LCD con la información de movimiento detectado y  respondiendo en caso de que se detecte movimiento llamando a la función Estados().',['../sketch_8ino.html#autotoc_md55',1,'']]],
  ['funcionamiento_20llamando_20a_20las_20funciones_20correspondientes_20si_20se_20introduce_20una_20opción_20no_20válida_20simplemente_20se_20limpia_20la_20selección_20y_20se_20vuelve_20a_20mostrar_20el_20menú_16',['PURPOSE: Permite al usuario interactuar con el menú principal, seleccionando opciones para configurar umbrales o cambiar el modo de funcionamiento llamando a las funciones correspondientes. Si se introduce una opción no válida, simplemente se limpia la selección y se vuelve a mostrar el menú.',['../sketch_8ino.html#autotoc_md31',1,'']]],
  ['funciones_20correspondientes_20si_20se_20introduce_20una_20opción_20no_20válida_20simplemente_20se_20limpia_20la_20selección_20y_20se_20vuelve_20a_20mostrar_20el_20menú_17',['PURPOSE: Permite al usuario interactuar con el menú principal, seleccionando opciones para configurar umbrales o cambiar el modo de funcionamiento llamando a las funciones correspondientes. Si se introduce una opción no válida, simplemente se limpia la selección y se vuelve a mostrar el menú.',['../sketch_8ino.html#autotoc_md31',1,'']]]
];
